### ISSUE TITLE
如何将该项目编译成网页以及如何参与到该项目中

### ISSUE THREAD

**Issue by Taoger-Xu** [masa-laboratory/GPGPUArchSim#1]
想问一下这个是用什么技术搭建的在线网站，如何参与到该项目中，这个项目的目标是gpgpu-sim-with-comments吗

**Comment by ConvolutedDog** [comment]
您好，这个是用  [sphinx-doc](https://www.sphinx-doc.org/en/master/) + Markdown 书写的代码注释，Github Pages 自动部署的网页。

这个项目主要是想把我们现在积累的 gpgpu-sim 整个建模过程以及 GPU 的微架构写一本在线的教程，欢迎加入进来，我们会提供有详细注释版本的 gpgpu-sim 代码，可以边学习边整理。

可以通过微信联系，15014212371。
